### ISSUE TITLE
Remove `gdata/{project}` from storage flags

### ISSUE THREAD

**Issue by SeanBryan51** [CABLE-LSM/benchcab#100]
We should not use the `gdata/{project}` storage flag in [the job script](https://github.com/CABLE-LSM/benchcab/blob/master/benchcab/job_script.py) as this is not necessary. Also, the project should only be used for specifying the `#PBS -P` flag in the job script.

**Comment by bschroeter** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/CABLE-Dev-643e35a4354310001fc40202/issues/CABLE-LSM/benchcab/100?planning-poker) with Zenhub @ccarouge @SeanBryan51
