### ISSUE TITLE
We should be using the logging module

### ISSUE THREAD

**Issue by SeanBryan51** [CABLE-LSM/benchcab#103]
Passing the `verbose` flag everywhere in the code base is not maintainable. We can avoid this by setting the verbosity level globally in the code base and use logging to output messages.

Useful links / resources:
- https://stackoverflow.com/questions/14097061/easier-way-to-enable-verbose-logging
- https://stackoverflow.com/questions/5980042/how-to-implement-the-verbose-or-v-option-into-a-script
- For testing logging with pytest https://docs.pytest.org/en/7.1.x/how-to/logging.html

**Comment by bschroeter** [comment]
The other way to do this is with a Singleton logging object that gets instantiated once at entry point.

I'll look into it.

**Comment by bschroeter** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/CABLE-Dev-643e35a4354310001fc40202/issues/CABLE-LSM/benchcab/103?planning-poker) with Zenhub @ccarouge @SeanBryan51

**Comment by bschroeter** [comment]
@SeanBryan51, this is basically done, however I had to back out several changes as many of the tests rely on assertions against stdout.

Do you have a plan going forward for doing tests against stdout? I don't think it is maintainable to for specific log messages when each log entry is timestamped.

Did you ever look into subprocess mock?

**Comment by SeanBryan51** [comment]
I have to admit the assertions against stdout might not be the best approach as I've found maintaining those to be a pain. It could be worth rethinking how or if we should test stdout.

On time stamped log entries, can we have time stamps disabled by default and enabled for a special 'debug' mode?
