### ISSUE TITLE
Add badges to README

### ISSUE THREAD

**Issue by SeanBryan51** [CABLE-LSM/benchcab#108]
We should add badges for:
- [x] Documentation. See https://docs.readthedocs.io/en/stable/badges.html for RTD.
- [ ] ~~CI Workflows. See https://docs.github.com/en/actions/monitoring-and-troubleshooting-workflows/adding-a-workflow-status-badge.~~
- [x] Conda package version (should link to the conda package url). See https://shields.io/badges/conda-2 or https://anaconda.org/accessnri/benchcab/badges.
- [x] License (should link to LICENSE). See: https://shields.io/badges/git-hub. **TODO**: need to add an Apache License 2.0 in repository.

**Comment by bschroeter** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/CABLE-Dev-643e35a4354310001fc40202/issues/CABLE-LSM/benchcab/108?planning-poker) with Zenhub @ccarouge @SeanBryan51

**Comment by SeanBryan51** [comment]
Closing this issue as key badges are now in the README.
