### ISSUE TITLE
Create an example run directory for spatial

### ISSUE THREAD

**Issue by ccarouge** [CABLE-LSM/benchcab#112]

**Comment by ccarouge** [comment]
We need to use Yingping's run directory example (/g/data/tm70/ccc561/CABLE/CABLE-as-ACCESS_Yingping) to create an example run directory for spatial tasks.

- [ ] remove CASA from the run.
- [ ] make the namelist file as similar to the site runs. This isn't completely necessary but prevents us from eventual complications due to CABLE options.

**Comment by SeanBryan51** [comment]
Closing as duplicate of https://github.com/CABLE-LSM/benchcab/issues/5
