### ISSUE TITLE
Add license and branding

### ISSUE THREAD

**Issue by ccarouge** [CABLE-LSM/benchcab#118]
We need to:
- add the Apache License file
- add NRI branding to the documentation
- add an acknowledgement section to the documentation
- review message on how to get support
- publish on Zenodo

**Comment by bschroeter** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/CABLE-Dev-643e35a4354310001fc40202/issues/CABLE-LSM/benchcab/118?planning-poker) with Zenhub @ccarouge @SeanBryan51
