### ISSUE TITLE
Handling of non-zero exit code from process (multiprocessing)

### ISSUE THREAD

**Issue by SeanBryan51** [CABLE-LSM/benchcab#122]
We currently don't exit with non-zero if a multiprocessing thread/process fails.

E.g. running `benchcab fluxsite-submit-job` without first running `benchcab fluxsite-setup-work-dir` should fail as the run directory has not been generated. However, `benchcab` still exit successfully. We need to check processes were successful by inspecting the exit code of each multiprocessing process.

This could also be a good opportunity to use `multiprocessing.Pool` instead of `multiprocessing.Queue`.

**Comment by bschroeter** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/CABLE-Dev-643e35a4354310001fc40202/issues/CABLE-LSM/benchcab/122?planning-poker) with Zenhub @ccarouge @SeanBryan51

**Comment by SeanBryan51** [comment]
I may have just realised why the current behaviour is the way it is. By letting `benchcab fluxsite-run-tasks` exit successfully regardless of the exit code of each task, we can run bitwise comparisons checks on whatever output files were produced without having any task dependence on the return code of CABLE tasks.

This issue makes me think this approach is not the best. Is there a better way without having some sort of task dependency between comparison tasks and running CABLE tasks (i.e. #157)?

**Comment by SeanBryan51** [comment]
On second thought I may have misinterpreted the issue. We can handle exceptions specific to running CABLE within each child process (i.e. suppress the exception) but any exceptions outside of that should be propagated to the parent process as this could signal something has gone wrong internally in benchcab.

**Comment by ccarouge** [comment]
For the moment, I don't mind if the bitwise comparison ignores the return status of the tasks that are running CABLE. In other words, I don't mind if we report an error code from a task and then go on and run the bitwise comparison anyway. It will just tell the users the comparison fails. I don't think we need to worry about dependencies yet even if we catch and report errors from CABLE.

But it would be good if when running all the tasks, we get:

- a message "Tasks have finished but some have failed" or "All tasks returned successfully"
- a list of failed tasks somewhere in the PBS log (it does not have to be at the end of running the tasks...).

Additionally, separating the benchcab errors from the CABLE errors is also a good idea.

**Comment by SeanBryan51** [comment]
> But it would be good if when running all the tasks, we get:
> 
> * a message "Tasks have finished but some have failed" or "All tasks returned successfully"
> * a list of failed tasks somewhere in the PBS log (it does not have to be at the end of running the tasks...).

This shouldn't be too difficult. We can store the status of each task as an attribute in the `Task` class, iterate over the tasks, and log which tasks failed.

**Comment by SeanBryan51** [comment]
Using `multiprocessing.Pool.map()` will kill all processes if any one process throws an exception. This seems like reasonable behaviour for when benchcab specific errors/exceptions occur.

In `run_tasks_in_parallel()`, we can have something like
```python
    run_task = operator.methodcaller("run", verbose=verbose)
    with multiprocessing.Pool(n_processes) as pool:
        pool.map(run_task, tasks, chunksize=1)
```

**Comment by SeanBryan51** [comment]
I've created an issue for logging a run summary of tasks to standard output in issue #180
