### ISSUE TITLE
Switch job script creation to Jinja2

### ISSUE THREAD

**Issue by bschroeter** [CABLE-LSM/benchcab#142]
It would be good to have the job script creation done with templates to move the string interpolation out of the source code.

I.e.

https://github.com/CABLE-LSM/benchcab/blob/b5fe7fd12c2670c15a4d4b8269cfdccce521fede/benchcab/utils/pbs.py#L8

Further, this can be used for any string interpolation (i.e. CLI commands etc.)

Would we need a set of configuration options to hold any string templates?

**Comment by SeanBryan51** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/CABLE-Dev-643e35a4354310001fc40202/issues/CABLE-LSM/benchcab/142?planning-poker) with Zenhub @bschroeter @ccarouge

**Comment by ccarouge** [comment]
Work on this after we have implemented a pyproject.toml to handle a data directory.

**Comment by SeanBryan51** [comment]
Since we don't want to implement pyproject.toml configuration yet. Can we achieve the same thing with the current PBR build configuration?

**Comment by SeanBryan51** [comment]
Jinja templating for the job script was added in https://github.com/CABLE-LSM/benchcab/pull/254
