### ISSUE TITLE
config.yaml input validation

### ISSUE THREAD

**Issue by SeanBryan51** [CABLE-LSM/benchcab#143]
Currently benchcab doesn't raise an exception if you give it an invalid key.

Ben suggested using [cerberus](https://docs.python-cerberus.org/) for doing input validation on python dictionaries.

Another option is [schema](https://github.com/keleshev/schema).

**Comment by SeanBryan51** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/CABLE-Dev-643e35a4354310001fc40202/issues/CABLE-LSM/benchcab/143?planning-poker) with Zenhub @bschroeter @ccarouge

**Comment by bschroeter** [comment]
This is basically complete, but there appears to be an issue with the conda version of cerberus 1.3.4. They have an approved but unmerged PR here (https://github.com/conda-forge/cerberus-feedstock/pull/15) that I've just nudged them on. Once they update their conda recipe I'll be able to open a PR.

**Comment by bschroeter** [comment]
Cerberus is updated - waiting on #172 to rebase/merge from.
