### ISSUE TITLE
Switch linting to ruff.

### ISSUE THREAD

**Issue by bschroeter** [CABLE-LSM/benchcab#145]
Ruff is 1000x faster for linting.

https://docs.astral.sh/ruff/

Is it worth switching it out?

**Comment by bschroeter** [comment]
Voting low because I think there is already a PR for this?

**Comment by ccarouge** [comment]
The linting comes from [dev-docs](https://github.com/ACCESS-NRI/dev-docs/wiki/Code-guidelines#linting-and-formatting) recommendation so opening an issue there as well to update these recommendations if possible.

**Comment by SeanBryan51** [comment]
We should think about what linting rules we want to include: https://docs.astral.sh/ruff/rules/
