### ISSUE TITLE
Log version of benchcab in output metadata

### ISSUE THREAD

**Issue by bschroeter** [CABLE-LSM/benchcab#147]
Add the benchcab version to the file metadata and report the version in any logging (see #103)

**Comment by SeanBryan51** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/CABLE-Dev-643e35a4354310001fc40202/issues/CABLE-LSM/benchcab/147?planning-poker) with Zenhub @bschroeter @ccarouge
