### ISSUE TITLE
Rename master to main?

### ISSUE THREAD

**Issue by bschroeter** [CABLE-LSM/benchcab#148]
Sean wants to "be up with the times" - should we rename master to main - are there any downstream consequences?

**Comment by SeanBryan51** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/CABLE-Dev-643e35a4354310001fc40202/issues/CABLE-LSM/benchcab/148?planning-poker) with Zenhub @bschroeter @ccarouge

**Comment by ccarouge** [comment]
Done
