### ISSUE TITLE
General tidy up of code.

### ISSUE THREAD

**Issue by bschroeter** [CABLE-LSM/benchcab#149]
Leave examples of code to be refactored?

Use this issue to track things that aren't necessarily an issue on their own.

If you need more than 2 lines to describe the thing, it is probably an issue.

**Comment by bschroeter** [comment]
https://github.com/CABLE-LSM/benchcab/blob/b5fe7fd12c2670c15a4d4b8269cfdccce521fede/benchcab/utils/logging.py#L6C8-L6C8

Why is this in logging?

**Comment by bschroeter** [comment]
https://github.com/CABLE-LSM/benchcab/blob/master/benchcab/internal.py

These look mostly like constants?

**Comment by SeanBryan51** [comment]
https://github.com/CABLE-LSM/benchcab/blob/162f5549eb6687281acbada931e9df54d7c1ec54/tests/test_repository.py#L191

`assert all()` does not tell you which `all` case caused it to evaluate to `False`. This should instead be split up into multiple asserts.

**Comment by SeanBryan51** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/CABLE-Dev-643e35a4354310001fc40202/issues/CABLE-LSM/benchcab/149?planning-poker) with Zenhub @bschroeter @ccarouge
