### ISSUE TITLE
Refactor work_dir creation

### ISSUE THREAD

**Issue by bschroeter** [CABLE-LSM/benchcab#150]
https://github.com/CABLE-LSM/benchcab/blob/master/benchcab/workdir.py

This could be handled by iterating through a list of paths to create the work dir. Configured internally somehow?

**Comment by SeanBryan51** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/CABLE-Dev-643e35a4354310001fc40202/issues/CABLE-LSM/benchcab/150?planning-poker) with Zenhub @bschroeter @ccarouge
