### ISSUE TITLE
Add revision number files to gitignore.

### ISSUE THREAD

**Issue by bschroeter** [CABLE-LSM/benchcab#154]
SVN revision numbers are stored in txt files in the work dir. They are ephemeral and should be ignored from git.

See [bench_example/.gitignore](https://github.com/CABLE-LSM/bench_example/blob/272455abb48201f55625b4aa86da160adae186c8/.gitignore)

**Comment by SeanBryan51** [comment]
Closing the issue as this has been fixed in https://github.com/CABLE-LSM/bench_example/pull/8
