### ISSUE TITLE
Better error handling in PBS job script

### ISSUE THREAD

**Issue by SeanBryan51** [CABLE-LSM/benchcab#158]
A better way of error handling in the PBS job script is to use `set -e` instead of a using bunch of if statements:

https://github.com/CABLE-LSM/benchcab/blob/b5fe7fd12c2670c15a4d4b8269cfdccce521fede/benchcab/utils/pbs.py#L53-L62

Helpful resource: https://intoli.com/blog/exit-on-errors-in-bash-scripts/

**Comment by ccarouge** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/CABLE-Dev-643e35a4354310001fc40202/issues/CABLE-LSM/benchcab/158?planning-poker) with Zenhub @bschroeter @SeanBryan51

**Comment by bschroeter** [comment]
See #158 for additional information.

This could be handled in #142 when we switch to Jinja2.

Voting heavy to align with other issues.
