### ISSUE TITLE
not extracting the correct trunk

### ISSUE THREAD

**Issue by har917** [CABLE-LSM/benchcab#16]
I have attempted to run benchcab using the trunk@9003 and my branch inh599/Ticket206 - and got a weird set of results comparing the two.

In chasing this down a bit further it appears that although the svn checkout step claimed it had extracted the trunk@9003 the srouce code (specifically the contents of the science/canopy sub-directory) do not match what's on the trac.

For example the benchcab extraction has 3 files (cable_canopy.F90 cbl_LAI_canopy_height.F90 and cable_canopy_explicit.F90) whereas the current trunk (@9000) has 13 files.  

It appears that something has gone awry with benchcab [and also gone awry in the process of splitting the cable_canopy directory into smaller modules]

**Comment by ccarouge** [comment]
I found the issue. The original code creates a copy of the trunk as a User branch and then checkout that copy. But for some reason, the code had some checks to **avoid** updating the trunk's copy. My guess is this is to allow running tests always against the same copy of trunk.
For the solution, there are 2 ways:

- removing the possibility to run against a fix version of trunk altogether and simply checkout the HEAD of trunk if we specify the trunk as the source. One can reproduce the functionality by creating a copy of trunk at a given revision in their own branches and use that as one of the branches to use for benchcab.
- modify the config.yaml file so we can specify a version number when describing the branches. 
I'll implement the second choice as this makes it easier no matter what type of branch is specified (trunk, User, Share) and would work similarly if we move CABLE to Git.
