### ISSUE TITLE
Remove `numpy` from `benchcab-dev.yaml`

### ISSUE THREAD

**Issue by SeanBryan51** [CABLE-LSM/benchcab#160]
Remove `numpy` from dependencies in dev conda environment.

https://github.com/CABLE-LSM/benchcab/blob/b5fe7fd12c2670c15a4d4b8269cfdccce521fede/.conda/benchcab-dev.yaml#L9

**Comment by ccarouge** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/CABLE-Dev-643e35a4354310001fc40202/issues/CABLE-LSM/benchcab/160?planning-poker) with Zenhub @bschroeter @SeanBryan51
