### ISSUE TITLE
Excessive output in job script from `set -ex`

### ISSUE THREAD

**Issue by SeanBryan51** [CABLE-LSM/benchcab#174]
The PBS job script produces a lot of excessive output from the `module purge` and `module load <module>` commands. This can be fixed easily by enabling the `set` options after the `module` commands.

I also propose using `set -ev` since the job script is not complex.

See [here](https://www.gnu.org/software/bash/manual/html_node/The-Set-Builtin.html) for man pages on the set builtin.

To reproduce:
```bash
#!/bin/bash
bench_example_dir='bench_example_test_AU-Tum_experiment'
rm -rf $bench_example_dir
git clone git@github.com:CABLE-LSM/bench_example.git $bench_example_dir
cd $bench_example_dir
git reset --hard 6287539e96fc8ef36dc578201fbf9847314147fb
cat > config.yaml << EOL
project: tm70

experiment: AU-Tum

realisations:
  - path: trunk

modules: [
  intel-compiler/2021.1.1,
  netcdf/4.7.4,
  openmpi/4.1.0
]
EOL
benchcab run -v
```

**Comment by ccarouge** [comment]
Agree! I was just coming here to say the same thing!

**Comment by ccarouge** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/benchcab-65237c1b3bde255f7a85afe4/issues/CABLE-LSM/benchcab/174?planning-poker) with Zenhub @bschroeter @SeanBryan51
