### ISSUE TITLE
Log run summary of tasks to standard output

### ISSUE THREAD

**Issue by SeanBryan51** [CABLE-LSM/benchcab#180]
It would be good if when running all the tasks, we get:

- a message "Tasks have finished but some have failed" or "All tasks returned successfully"
- a list of failed tasks somewhere in the PBS log (it does not have to be at the end of running the tasks...).

_Originally posted by @ccarouge in https://github.com/CABLE-LSM/benchcab/issues/122#issuecomment-1758839844_

One approach could be to store the status of each task as an attribute in the Task class, then iterate over the tasks, and log which tasks failed.

**Comment by ccarouge** [comment]
Since we discussed doing something like that today when discussing the meorg API implementation, I'm putting this to high priority.
