### ISSUE TITLE
Make `get_fluxnet_tasks` a generator instead of returning a list of tasks

### ISSUE THREAD

**Issue by ccarouge** [CABLE-LSM/benchcab#24]
It seems more logical for this function to be a generator. We will have to be careful on how to handle it in `benchsiterun` since it is using indexing to reach specific tasks.

**Comment by SeanBryan51** [comment]
Closing this issue since we likely have to iterate over the list of tasks multiple times, in this case it is more efficient to store the list of tasks in memory.
