### ISSUE TITLE
Test for validation for `project` value

### ISSUE THREAD

**Issue by abhaasgoyal** [CABLE-LSM/benchcab#246]
Right now, a user can input any value in $PROJECT / project keyword in `config.yaml`. It isn't checked whether the user belongs to a certain group until the job has been submitted to PBS. 

## Reproduce

Run benchcab with the following parameter

```yaml
project: optional

...
```

## Next steps

Add a validation check by checking the groups of a user, and whether `project` lies within the corresponding set

**Comment by abhaasgoyal** [comment]
We could use a subprocess for `lquota` - but that'd be very specific to Gadi in terms of unit tests, as well as slow.

Since running an invalid project name on PBS could provide an error, do we still need this at an earlier steps (potentially to make `benchcab` more user-friendly? Also, are there other ways to check which groups is a user in

**Comment by SeanBryan51** [comment]
Benchcab should complain if the project is not in the groups of the user, but it isn't that user friendly:

**Comment by abhaasgoyal** [comment]
Yeah it seems good, is it fine if I just edit the message to be
```
Error: User is not a member of project(s):
", ".join([non_existing])
Check if project key is correct, or the user has the necessary group permissions
```

**Comment by abhaasgoyal** [comment]
I see, maybe we could edit the message and add the necessary unit tests (although it would be tricky since the function depends on Gadi environment)
