### ISSUE TITLE
Add quick start instructions for users on Gadi

### ISSUE THREAD

**Issue by SeanBryan51** [CABLE-LSM/benchcab#277]
It would be useful to have all the instructions needed to run benchcab on Gadi without having to read the full explanation of each step in the documentation as this will be clearer for users to get started (see #276).

For example, we could have the following as the first section in the README or the main documentation:

## Quickstart

To launch a benchcab run, execute the following in the command line:

```bash
module use /g/data/hh5/public/modules
module load conda/analysis3-unstable
cd /scratch/$PROJECT/$USER
git clone https://github.com/CABLE-LSM/bench_example.git
cd bench_example
benchcab run
```

**Comment by ccarouge** [comment]
Maybe add the manual edit of the config file to the list of commands?
```shell
module use /g/data/hh5/public/modules
module load conda/analysis3-unstable
cd /scratch/$PROJECT/$USER
git clone https://github.com/CABLE-LSM/bench_example.git
cd bench_example
# Edit config.yaml to your liking
vim config.yaml
benchcab run
```
