### ISSUE TITLE
Bitwise comparisons: confusing message to users

### ISSUE THREAD

**Issue by ccarouge** [CABLE-LSM/benchcab#299]
Currently, the code will print to log we are running comparison tests and the success of the tests **even** when we run only 1 realisation. In that case, there are no comparison tasks to run. It might be good to change the messages if `comparisons` is empty.

https://github.com/CABLE-LSM/benchcab/blob/fc625c0fb07a52a2b9987ccf33ecfe7bd35556c7/src/benchcab/benchcab.py#L320-L326

**Comment by SeanBryan51** [comment]
This reminded me of PR #291. In that PR, the log messages around fluxsite tasks and comparison tasks are improved to output the total number of tasks as well as how many succeeded/failed (for example see [here](https://github.com/CABLE-LSM/benchcab/pull/291#discussion_r1606182561)). Does this address your issue?

**Comment by ccarouge** [comment]
Yes. And sorry the review request got lost it seems.
