### ISSUE TITLE
Use local checkout of CABLE

### ISSUE THREAD

**Issue by ccarouge** [CABLE-LSM/benchcab#33]
Currently, benchcab will checkout the control and the development branches from the SVN repository. This means users can't use benchcab to test their development before committing to SVN.

It would be best if a realisation could be specified using a local path instead of an SVN branch. 

Open question: compilation takes a long time. Should we allow using a pre-compiled executable if using a local path? Should we have a way to identify this in the analysis in me.org so the results can't be used in a PR to CABLE? For PR review, we want to ensure benchcab runs from the head of the branch on the remote repository.

Idea: use symlink to the local dir. Careful with clean!

This includes:

- copy from local path. Copy allows to test on uncommitted changes.
- think about re-run of benchcab.

**Comment by bschroeter** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/CABLE-Dev-643e35a4354310001fc40202/issues/CABLE-LSM/benchcab/33?planning-poker) with Zenhub @ccarouge @SeanBryan51
