### ISSUE TITLE
It is too long to get feedback if there is an error in science configuration provided

### ISSUE THREAD

**Issue by ccarouge** [CABLE-LSM/benchcab#47]
Currently, it is possible for `benchcab` to write garbage to the namelist file from wrong inputs and then we have to wait for the checkout, build and run to get the information the namelist is wrong.

Then, when we correct the input information, we have to wait through the whole time again.

We need to change this to either:

- check the namelist information from `benchcab` (difficult)
- only checkout/build the code when required so the feedback comes back earlier (easier) and send feedback to the user about a failed run.

**Comment by bschroeter** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/CABLE-Dev-643e35a4354310001fc40202/issues/CABLE-LSM/benchcab/47?planning-poker) with Zenhub @ccarouge @SeanBryan51

**Comment by bschroeter** [comment]
I feel like this can be addressed somewhat with configuration validation. #143

**Comment by SeanBryan51** [comment]
> only checkout/build the code when required so the feedback comes back earlier (easier) and send feedback to the user about a failed run.

Iterative builds in benchcab are possible due to the recent CMake changes in CABLE. Parallelised builds are also now enabled by default which improve build times. Closing this issue for now.
