### ISSUE TITLE
Remove synonymous names for `fluxnet`

### ISSUE THREAD

**Issue by SeanBryan51** [CABLE-LSM/benchcab#62]
We should remove synonymous names in code for `fluxnet` to prevent confusion. For example: `site`, `single sites`, `fluxsite`, `fluxnet site`, etc.

Note "fluxnet" should be capitalised when written outside of code: see https://fluxnet.org/.

**Comment by SeanBryan51** [comment]
**API change proposal**: replace `fluxnet` with `fluxsite` (the latter is a better name for describing the nature of the tests).

**Comment by ccarouge** [comment]
I think it is good to go with `fluxsite`. It is maybe less transparent to the community as not being a commonly used term. But it avoids referring to a specific product (or network). And for the spatially gridded runs, we won't be referring to a specific product so it will work best together.
