### ISSUE TITLE
Polished messaging to standard output

### ISSUE THREAD

**Issue by ccarouge** [CABLE-LSM/benchcab#67]
Currently, `benchcab` outputs stdout from other commands such as `svn` and `./build3.sh`, but does not output anything when running `./cable` or when generating particular directory structures. This can be improved by having `benchcab` print helpful messages to stdout so that the user is made aware of what `benchcab` is doing.

**Comment by SeanBryan51** [comment]
## Draft requirements

Draft requirements for what stdout should look like for various commands

### When checking out CABLE via `svn`:
by default
```
$ benchcab checkout
Checking out repositories...
Successfully checked out <branch_name> at revision <revision>
Writing revision number in rev_number-0.log.
```
with verbose `-v` option:
- print all output from the non-verbose case
- print the svn command used to checkout repo
- print all output from the svn command
```
$ benchcab checkout
Checking out repositories...
svn checkout https://trac.nci.org.au/svn/cable/<path_to_branch> src/<branch_name>
A    src/<branch_name>/offline
A    src/<branch_name>/offline/cable_mpiworker.F90
A    src/<branch_name>/offline/serial_cable
A    src/<branch_name>/offline/cable_LUC_EXPT.F90
...
A    src/<branch_name>/util/cable_common.F90
A    src/<branch_name>/util/masks_cbl.F90
A    src/<branch_name>/util/cable_climate_type_mod.F90
 U   src/<branch_name>
Checked out revision <revision>.
Successfully checked out <branch_name> at revision <revision>
Writing revision number in rev_number-0.log.
```

**Comment by SeanBryan51** [comment]
@ccarouge I've added a rough draft for what I think we should output to stdout. Please feel free to add or change the output in the rough draft.

**Comment by ccarouge** [comment]
During compilation, I would specify "serially / with MPI".
For `fluxnet-setup-work-dir`, I would start with a generic sentence, something like: "setting up run directory tree for flux sites tests". And maybe just list the logs, outputs and tasks paths in the default output. The "runs" and "site" paths aren't useful information.

For CABLE stdout, I would send it to a file in the tasks directory in all cases. So we save it but don't output to screen.
In verbose version, we could output something like: "Running task X. CABLE standard output saved in /path/to/file".

**Comment by SeanBryan51** [comment]
Thanks for the feedback. I've made those changes to the draft

**Comment by ccarouge** [comment]
Added a few more details for the case `$ benchcab fluxnet-run-tasks`, non-verbose. So people know where all outputs are.

**Comment by SeanBryan51** [comment]
I've just made an edit to keep `<task_name>` when describing the location of outputs for `$ benchcab fluxnet-run-tasks`

**Comment by ccarouge** [comment]
Edit: more details about what the PBS script is for under `$ benchcab fluxnet-run-tasks`
