### ISSUE TITLE
Update the documentation properly once the versioning is in place.

### ISSUE THREAD

**Issue by ccarouge** [CABLE-LSM/benchcab#70]

**Comment by ccarouge** [comment]
Updates needed:

- use list of dict for `realisation`
- add `build_script` option
- change User guide to use sub-commands and not command line options

@SeanBryan51 anything else?

**Comment by SeanBryan51** [comment]
That sounds about right. Should we add stuff from more recent work such as #69 and #76?

**Comment by ccarouge** [comment]
I'm happy to add stuff about #69 on the output messages because it should get into the code base soon, likely before the PR for this issue. But for #76, I'd prefer the update to the documentation to be a part of the same PR as the work on the code itself, since it will come in later.
