### ISSUE TITLE
Should we add a reverse patch option?

### ISSUE THREAD

**Issue by SeanBryan51** [CABLE-LSM/benchcab#92]
We should cater for the use case when a branch does not support a namelist parameter in the base namelist file. See [here](https://github.com/CABLE-LSM/bench_example_GW/commit/d1f08654645e247fca46a723aa00673b48bd4339) for example. Ideally the user should not remove namelist parameters from the base namelist file as this will effect the namelist parameters for all branches.

Should we add a "reverse patch" option for each branch that will remove a given namelist parameter for that branch? And should we keep the base namelist file internal to benchcab to prevent users from modifying the base namelist file?

**Comment by ccarouge** [comment]
Ideally, this would not be needed as branches that are compared together are not too old. So this is only needed to deal with historical cases. We'll have to see whether it is worth the effort to implement a reverse patch. Or am I missing a use-case?

The namelist file should be internal to benchcab but only if we have a reverse patch or we reach the state we don't need a reverse patch.

**Comment by SeanBryan51** [comment]
Yes this issue is related to running legacy CABLE branches. Also, we discussed a while back that we should not rely on the default values for namelist parameters. If we remove a parameter from base namelist file like what was done in GW example above, we are depending on the default value in every branch which could be problematic.

**Comment by ccarouge** [comment]
OK, let's implement it.

**Comment by ccarouge** [comment]
Let's not put the namelist internal to benchcab because this could be problematic if we decide to split the namelist file into several files.
