### ISSUE TITLE
Releases should create a new version for the docs

### ISSUE THREAD

**Issue by ccarouge** [CABLE-LSM/benchcab#93]
When we tag a version for a release and release that version, we should automatically create a version of the documentation using that tag. It is the same as the `stable` and `latest` versions at that time but it will diverge later on.

**Comment by ccarouge** [comment]
Check if it has been done on readthedocs.

**Comment by bschroeter** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/CABLE-Dev-643e35a4354310001fc40202/issues/CABLE-LSM/benchcab/93?planning-poker) with Zenhub @ccarouge @SeanBryan51

**Comment by SeanBryan51** [comment]
I've just checked this for the recent release and the v3.0.0 documentation is available: https://benchcab.readthedocs.io/en/v3.0.0/

Since it looks like it's working, I will close the issue.
